[build]
functions = "netlify/functions"
publish = "."

[functions]
node_bundler = "esbuild"
external_node_modules = ["node-fetch"]

[[redirects]]
from = "/api/ai-proxy"
to = "/.netlify/functions/ai-proxy"
status = 200
force = true
